parameters:
#    tutorial_chapter9.example.class: Tutorial\Chapter9Bundle\Example

services:
#    tutorial_chapter9.example:
#        class: %tutorial_chapter9.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
