parameters:
#    example1_job.example.class: Example1\JobBundle\Example

services:
#    example1_job.example:
#        class: %example1_job.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
